list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/../..")
include(base_config)

list(APPEND CMAKE_MODULE_PATH "${NUGGET_LIBRARY_PATH}")
include(Nugget)

set(TARGET_NAME "papi_nugget_bc")
set(HOOK_TARGET single-threaded-papi-nugget)

# Pull required paths from environment; fail fast if missing.
if (NOT DEFINED ENV{ALL_NUGGET_RIDS_FILE} OR "$ENV{ALL_NUGGET_RIDS_FILE}" STREQUAL "")
	message(FATAL_ERROR "Environment variable ALL_NUGGET_RIDS_FILE must be set")
endif()
if (NOT DEFINED ENV{MARKER_DIR} OR "$ENV{MARKER_DIR}" STREQUAL "")
	message(FATAL_ERROR "Environment variable MARKER_DIR must be set")
endif()
if (NOT DEFINED ENV{SOURCE_BC_FILE_PATH} OR "$ENV{SOURCE_BC_FILE_PATH}" STREQUAL "")
	message(FATAL_ERROR "Environment variable SOURCE_BC_FILE_PATH must be set")
endif()
if (NOT DEFINED ENV{BB_INFO_INPUT_PATH} OR "$ENV{BB_INFO_INPUT_PATH}" STREQUAL "")
	message(FATAL_ERROR "Environment variable BB_INFO_INPUT_PATH must be set")
endif()
set(BB_INFO_INPUT_PATH $ENV{BB_INFO_INPUT_PATH})
set(ALL_NUGGET_RIDS_FILE $ENV{ALL_NUGGET_RIDS_FILE})
if(NOT EXISTS ${ALL_NUGGET_RIDS_FILE})
	message(FATAL_ERROR "ALL_NUGGET_RIDS_FILE ${ALL_NUGGET_RIDS_FILE} does not exist")
endif()
nugget_read_list(ALL_NUGGET_RIDS ${ALL_NUGGET_RIDS_FILE})
set(ALL_MARKER_DIR $ENV{MARKER_DIR})
set(MARKER_CONFIG_FILE_EXT "-marker.txt")
set(SOURCE_BC_FILE_PATH $ENV{SOURCE_BC_FILE_PATH})
set(SOURCE_BC_FILE_BASENAME "lsms_ir_bb_analysis_bc")

set(BB_INFO_OUTPUT_DIR ${CMAKE_CURRENT_BINARY_DIR}/nugget-bb-info-output)
